version: '3'
services:
  web:
    build: ./web
    depends_on:
      - "db"
      - "mediaserver"
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
  db:
    build: ./db
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=better-reflectapp-admin"
      - "MONGO_INITDB_ROOT_PASSWORD=example123"
      - "MONGO_INITDB_DATABASE=better-reflectapp"
    restart: unless-stopped
  mediaserver:
    build: ./mediaserver
    ports:
      - "127.0.0.1:3005:3005"
    volumes:
      - "./media:/usr/src/app/media"
    restart: unless-stopped
